USE [NCB_MIG]
GO

/****** Object:  UserDefinedFunction [dbo].[Dzielenie]    Script Date: 2022-08-23 14:47:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[Dzielenie](@Klucz_PH nvarchar(255), @Nazwa nvarchar(255))

RETURNS @tabela TABLE (KLUCZ_PH nvarchar(255), NAZWA_1 nvarchar(40), NAZWA_2 nvarchar(40), NAZWA_3 nvarchar(40), NAZWA_4 nvarchar(40))
AS 
BEGIN 

DECLARE @Tab_1 TABLE (ID int IDENTITY(1,1),
					KLUCZ_PH nvarchar(255),
					NAZWA nvarchar(255),
					ILE int)
DECLARE @NAZWA_1 nvarchar(40)
DECLARE @NAZWA_2 nvarchar(40)
DECLARE @NAZWA_3 nvarchar(40)
DECLARE @NAZWA_4 nvarchar(40)

INSERT INTO @Tab_1(NAZWA) SELECT VALUE FROM string_split(@Nazwa,' ') AS NAZWA;

WITH A AS(
SELECT NAZWA, 
		SUM(LEN(NAZWA)+1) OVER (ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ILE_1, 
		ILE
FROM @Tab_1)

UPDATE A
	SET ILE = ILE_1;
	SET @NAZWA_1 = (SELECT STRING_AGG(NAZWA, ' ') FROM @Tab_1 WHERE ILE<=40);
	DELETE @Tab_1 WHERE ILE<=40;

WITH A AS(
SELECT NAZWA, 
		SUM(LEN(NAZWA)+1) OVER (ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ILE_1, 
		ILE
FROM @Tab_1)

UPDATE A
	SET ILE = ILE_1;
	SET @NAZWA_2 = (SELECT STRING_AGG(NAZWA, ' ') FROM @Tab_1 WHERE ILE<=40);
	DELETE @Tab_1 WHERE ILE<=40;

WITH A AS(
SELECT NAZWA, 
		SUM(LEN(NAZWA)+1) OVER (ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ILE_1, 
		ILE
FROM @Tab_1)

UPDATE A
	SET ILE = ILE_1;
	SET @NAZWA_3 = (SELECT STRING_AGG(NAZWA, ' ') FROM @Tab_1 WHERE ILE<=40);
	DELETE @Tab_1 WHERE ILE<=40;

WITH A AS(
SELECT NAZWA, 
		SUM(LEN(NAZWA)+1) OVER (ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ILE_1, 
		ILE
FROM @Tab_1)

UPDATE A
	SET ILE = ILE_1;
	SET @NAZWA_4 = (SELECT STRING_AGG(NAZWA, ' ') FROM @Tab_1 WHERE ILE<=40);
	DELETE @Tab_1 WHERE ILE<=40;

INSERT INTO @tabela (KLUCZ_PH , NAZWA_1 , NAZWA_2 , NAZWA_3 , NAZWA_4)
VALUES (@Klucz_PH, @NAZWA_1, @NAZWA_2, @NAZWA_3, @NAZWA_4)

RETURN;
END

GO

