USE [NCB_MIG]
GO

CREATE TABLE [hm].[Stg_PH](
	[nrpl] [nvarchar](255) NULL,
	[nip] [nvarchar](255) NULL,
	[regon] [nvarchar](255) NULL,
	[pesel] [nvarchar](255) NULL,
	[nazwa] [nvarchar](255) NULL,
	[ulica] [nvarchar](255) NULL,
	[kodpocztowy] [nvarchar](255) NULL,
	[miejscowosc] [nvarchar](255) NULL,
	[poczta] [nvarchar](255) NULL,
	[nrdomu] [nvarchar](255) NULL,
	[nrmieszkania] [nvarchar](255) NULL,
	[gus] [nvarchar](255) NULL,
	[nrrejonu] [nvarchar](255) NULL,
	[SystemZrodlowyId] [tinyint] NULL,
	--[id_grupa_wind] [int] NULL,
	--[biuro] [nvarchar](255) NULL,
	[kor_dom] [nvarchar](255) NULL,
	[kor_kod_poczt] [nvarchar](255) NULL,
	[kor_miejsc] [nvarchar](255) NULL,
	[kor_mieszk] [nvarchar](255) NULL,
	[kor_poczta] [nvarchar](255) NULL,
	[kor_ulica] [nvarchar](255) NULL,
	--[tryb_koresp] [nvarchar](255) NULL,
	[mail] [nvarchar](255) NULL,
	[telefon] [nvarchar](255) NULL,
	--[telefon_kom] [nvarchar](255) NULL,
	--[fax] [nvarchar](255) NULL,
	--[odbior] [nvarchar](255) NULL,
	--[id_sprzedawcy] [nvarchar](255) NULL,
	--[obrot_dystrybucja] [nvarchar](255) NULL,
	--[nr_seria_dowodu] [nvarchar](255) NULL,
	--[branza] [nvarchar](255) NULL,
	--[saldo] [nvarchar](255) NULL,
	--[DataImportu] [datetime] NULL,
	--[kor_nazwa1] [nvarchar](255) NULL,
	[kor_nazwa2] [nvarchar](255) NULL,
	[Klucz_PH] [varchar](17) NOT NULL,
	[CzyMIG] [int] NOT NULL,
	[PGE] [int] NULL,
	[N_Systemu] [varchar](50) NULL,
	[Oddzial] [varchar](3) NULL,
	[TERYT_MIEJSCOWOSC] [nvarchar](255) NULL,
	[KOR_TERYT_MIEJSCOWOSC] [nvarchar](255) NULL,
	[KRAJ] [nvarchar](2) NULL,
	[KOR_KRAJ] [nvarchar](2) NULL,
	[TERYT_ULICY] [nvarchar](255) NULL,
	[KOR_TERYT_ULICY] [nvarchar](255) NULL,
	[MIEJSCOWOSC_CLR] [nvarchar](255) NULL,
	[ULICE_CLR] [nvarchar](255) NULL,
	[KOD_POCZTOWY_POP] [nvarchar](6) NULL,
	[SUGEROWANY_TYP] [smallint] NULL,
	[CEIDG] [smallint] NULL
) 
GO

